function gradientCss(angle, startColor, endColor) {
  return `linear-gradient(${angle}deg, ${startColor} 0%, ${endColor} 100%)`;
}

function extractMainTextFontDefaults(fontString) {
  const match = fontString.match(/^(.+?\s)?(\d+)px\s+(.+)$/);
  if (!match) {
    return {
      mainTextFontFamily: "Arial, sans-serif",
      mainTextFontSize: 56,
    };
  }

  return {
    mainTextFontFamily: match[3].trim(),
    mainTextFontSize: parseInt(match[2], 10),
  };
}

function makeTemplate({
  id,
  name,
  description,
  preview,
  defaults,
  config,
  previewSeed,
}) {
  const fontDefaults = extractMainTextFontDefaults(config.mainTextField.font);
  return {
    id,
    name,
    description,
    preview,
    supportsIcon: true,
    defaults: {
      ...defaults,
      flipBackgroundPosition: defaults.flipBackgroundPosition || false,
      mainTextFontFamily:
        defaults.mainTextFontFamily || fontDefaults.mainTextFontFamily,
      mainTextFontSize:
        defaults.mainTextFontSize || fontDefaults.mainTextFontSize,
    },
    config,
    previewSeed: {
      ...previewSeed,
      mainTextFontFamily:
        previewSeed.mainTextFontFamily || fontDefaults.mainTextFontFamily,
      mainTextFontSize:
        previewSeed.mainTextFontSize || fontDefaults.mainTextFontSize,
      flipBackgroundPosition: previewSeed.flipBackgroundPosition || false,
    },
  };
}

const blueprintPalette = {
  dark: "#000000",
  frame: "#ffffff",
  primary: "#2f3f93",
  surface: "#d7e8f6",
  text: "#10233f",
};

function makeBlueprintTemplate({
  id,
  name,
  description,
  defaultName,
  defaultMainText,
  iconName,
  config,
  previewGradient = [blueprintPalette.primary, blueprintPalette.dark],
  previewAccentColor = blueprintPalette.primary,
}) {
  const defaults = {
    name: defaultName,
    mainText: defaultMainText,
    backgroundType: "color",
    backgroundColor: blueprintPalette.dark,
    backgroundGradientCss: gradientCss(
      120,
      blueprintPalette.primary,
      blueprintPalette.dark
    ),
    surfaceColor: blueprintPalette.surface,
    surfaceOpacity: 1,
    primaryColor: blueprintPalette.primary,
    mainTextColor: blueprintPalette.text,
    iconSource: "lucide",
    iconName,
    iconColor: "#ffffff",
    iconBackgroundColor: blueprintPalette.primary,
    flipBackgroundPosition: false,
  };

  return makeTemplate({
    id,
    name,
    description,
    preview: {
      bgGradient: previewGradient,
      accentColor: previewAccentColor,
    },
    defaults,
    previewSeed: defaults,
    config,
  });
}

export const templates = {
  classic: makeTemplate({
    id: "classic",
    name: "Classic",
    description: "Clean centered panel with elegant typography",
    preview: {
      bgGradient: ["#e8e4df", "#d4cfc9"],
      accentColor: "#c67c4e",
    },
    defaults: {
      name: "HEALTH AND WELLNESS",
      mainText: "How to Have a Better Work-Life Balance",
      backgroundType: "color",
      backgroundColor: "#e8e4df",
      backgroundGradientCss: gradientCss(45, "#e8e4df", "#d4cfc9"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.85,
      primaryColor: "#c67c4e",
      mainTextColor: "#1a1a1a",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#c67c4e",
    },
    previewSeed: {
      name: "HEALTH AND WELLNESS",
      mainText: "How to Have a Better Work-Life Balance",
      backgroundType: "color",
      backgroundColor: "#e8e4df",
      backgroundGradientCss: gradientCss(45, "#e8e4df", "#d4cfc9"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.85,
      primaryColor: "#c67c4e",
      mainTextColor: "#1a1a1a",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#c67c4e",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 45,
        startColor: "#e8e4df",
        endColor: "#d4cfc9",
      },
      surface: {
        type: "centered",
        height: 340,
        padding: 100,
        defaultColor: "#ffffff",
        defaultOpacity: 0.85,
      },
      icon: {
        x: 554,
        y: 68,
        size: 92,
        iconInset: 22,
        borderColor: "#ffffff",
        borderWidth: 4,
      },
      nameField: {
        font: "500 24px Arial, sans-serif",
        defaultColor: "#c67c4e",
        textTransform: "uppercase",
        letterSpacing: 4,
        offsetY: 70,
      },
      mainTextField: {
        font: '400 64px "Playfair Display", Georgia, serif',
        defaultColor: "#1a1a1a",
        lineHeight: 80,
        offsetY: 80,
        maxWidth: -220,
      },
    },
  }),
  minimal: makeTemplate({
    id: "minimal",
    name: "Minimal",
    description: "Clean editorial layout with subtle accents",
    preview: {
      bgGradient: ["#fafafa", "#f0f0f0"],
      accentColor: "#2563eb",
    },
    defaults: {
      name: "QUIET LUXURY",
      mainText: "Simple design choices that still feel premium",
      backgroundType: "color",
      backgroundColor: "#fafafa",
      backgroundGradientCss: gradientCss(135, "#fafafa", "#f0f0f0"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#2563eb",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "palette",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    previewSeed: {
      name: "QUIET LUXURY",
      mainText: "Simple design choices that still feel premium",
      backgroundType: "color",
      backgroundColor: "#fafafa",
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#2563eb",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "palette",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: "#fafafa",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 590,
          width: 1200,
          height: 40,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 100,
          y1: 200,
          x2: 300,
          y2: 200,
          strokeWidth: 3,
          colorRole: "primaryColor",
        },
      ],
      icon: {
        x: 556,
        y: 72,
        size: 88,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 0,
      },
      nameField: {
        font: "500 16px Arial, sans-serif",
        defaultColor: "#2563eb",
        textTransform: "uppercase",
        letterSpacing: 8,
        x: 100,
        y: 240,
        align: "left",
      },
      mainTextField: {
        font: "400 58px Lora, Georgia, serif",
        defaultColor: "#1f2937",
        lineHeight: 75,
        x: 100,
        y: 320,
        align: "left",
        maxWidth: 860,
      },
    },
  }),
  vibrant: makeTemplate({
    id: "vibrant",
    name: "Vibrant",
    description: "Colorful gradient background with a floating card",
    preview: {
      bgGradient: ["#667eea", "#f093fb"],
      accentColor: "#fbbf24",
    },
    defaults: {
      name: "CREATIVE SYSTEMS",
      mainText: "Build a content engine that feels bright and human",
      backgroundType: "gradient",
      backgroundColor: "#667eea",
      backgroundGradientCss: gradientCss(135, "#667eea", "#f093fb"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.95,
      primaryColor: "#7c3aed",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "star",
      iconColor: "#ffffff",
      iconBackgroundColor: "#f59e0b",
    },
    previewSeed: {
      name: "CREATIVE SYSTEMS",
      mainText: "Build a content engine that feels bright and human",
      backgroundType: "gradient",
      backgroundGradientCss: gradientCss(135, "#667eea", "#f093fb"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.95,
      primaryColor: "#7c3aed",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "star",
      iconColor: "#ffffff",
      iconBackgroundColor: "#f59e0b",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 135,
        startColor: "#667eea",
        endColor: "#f093fb",
      },
      decorations: [
        {
          type: "circle",
          x: 200,
          y: 100,
          radius: 80,
          color: "rgba(255, 255, 255, 0.1)",
        },
        {
          type: "circle",
          x: 1000,
          y: 500,
          radius: 120,
          color: "rgba(255, 255, 255, 0.08)",
        },
        {
          type: "circle",
          x: 900,
          y: 150,
          radius: 40,
          color: "rgba(255, 255, 255, 0.15)",
        },
      ],
      surface: {
        type: "floating",
        x: 100,
        y: 115,
        width: 1000,
        height: 400,
        defaultColor: "#ffffff",
        defaultOpacity: 0.95,
        borderRadius: 24,
        shadow: {
          blur: 60,
          color: "rgba(0, 0, 0, 0.25)",
          offsetY: 20,
        },
      },
      icon: {
        x: 551,
        y: 58,
        size: 98,
        iconInset: 22,
        borderColor: "rgba(255,255,255,0.5)",
        borderWidth: 3,
      },
      nameField: {
        font: "700 16px Arial, sans-serif",
        defaultColor: "#7c3aed",
        textTransform: "uppercase",
        letterSpacing: 6,
        y: 200,
        align: "center",
        badge: {
          enabled: true,
          padding: { x: 20, y: 10 },
          colorRole: "primaryColorSoft",
          borderRadius: 20,
        },
      },
      mainTextField: {
        font: "700 54px Montserrat, Arial, sans-serif",
        defaultColor: "#1f2937",
        lineHeight: 70,
        y: 290,
        align: "center",
        maxWidth: 760,
      },
    },
  }),
  socialMessage: makeTemplate({
    id: "socialMessage",
    name: "Social Message",
    description: "Social media-inspired message card with profile accent",
    preview: {
      bgGradient: ["#0f172a", "#60a5fa"],
      accentColor: "#2563eb",
    },
    defaults: {
      name: "@dailygrace",
      mainText: "Small reminders can reset the whole tone of your day.",
      backgroundType: "gradient",
      backgroundColor: "#0f172a",
      backgroundGradientCss: gradientCss(140, "#0f172a", "#60a5fa"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.97,
      primaryColor: "#2563eb",
      mainTextColor: "#1e293b",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    previewSeed: {
      name: "@dailygrace",
      mainText: "Small reminders can reset the whole tone of your day.",
      backgroundType: "gradient",
      backgroundGradientCss: gradientCss(140, "#0f172a", "#60a5fa"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.97,
      primaryColor: "#2563eb",
      mainTextColor: "#1e293b",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 140,
        startColor: "#0f172a",
        endColor: "#60a5fa",
      },
      decorations: [
        {
          type: "circle",
          x: 1020,
          y: 100,
          radius: 180,
          color: "rgba(255, 255, 255, 0.1)",
        },
        {
          type: "circle",
          x: 140,
          y: 530,
          radius: 150,
          color: "rgba(255, 255, 255, 0.08)",
        },
      ],
      surface: {
        type: "floating",
        x: 90,
        y: 75,
        width: 1020,
        height: 480,
        defaultColor: "#ffffff",
        defaultOpacity: 0.97,
        borderRadius: 36,
        shadow: {
          blur: 60,
          color: "rgba(15, 23, 42, 0.28)",
          offsetY: 24,
        },
      },
      icon: {
        x: 188,
        y: 136,
        size: 112,
        iconInset: 28,
        borderColor: "#ffffff",
        borderWidth: 8,
        shadow: {
          color: "rgba(15, 23, 42, 0.18)",
          blur: 24,
          offsetY: 12,
        },
      },
      nameField: {
        font: "700 30px Arial, sans-serif",
        defaultColor: "#2563eb",
        x: 314,
        y: 190,
        align: "left",
      },
      mainTextField: {
        font: '400 56px "DM Sans", Arial, sans-serif',
        defaultColor: "#1e293b",
        lineHeight: 66,
        x: 150,
        y: 320,
        align: "left",
        maxWidth: 860,
        maxLines: 4,
        minScale: 0.42,
      },
      subtitle: {
        enabled: true,
        font: "500 20px Arial, sans-serif",
        color: "#64748b",
        x: 150,
        y: 485,
        align: "left",
        text: "Reply  •  Share  •  Save",
      },
    },
  }),
  angledFrame: makeTemplate({
    id: "angledFrame",
    name: "Angled Frame",
    description: "Sharp geometric banner with a slanted content panel",
    preview: {
      bgGradient: ["#2f3f93", "#000000"],
      accentColor: "#2f3f93",
    },
    defaults: {
      name: "MARKETING INSIGHT",
      mainText: "Turn one strong message into a design system that scales.",
      backgroundType: "color",
      backgroundColor: "#000000",
      backgroundGradientCss: gradientCss(120, "#2f3f93", "#000000"),
      surfaceColor: "#d7e8f6",
      surfaceOpacity: 1,
      primaryColor: "#2f3f93",
      mainTextColor: "#10233f",
      iconSource: "lucide",
      iconName: "megaphone",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2f3f93",
      flipBackgroundPosition: false,
    },
    previewSeed: {
      name: "MARKETING INSIGHT",
      mainText: "Turn one strong message into a design system that scales.",
      backgroundType: "color",
      backgroundColor: "#000000",
      surfaceColor: "#d7e8f6",
      surfaceOpacity: 1,
      primaryColor: "#2f3f93",
      mainTextColor: "#10233f",
      iconSource: "lucide",
      iconName: "megaphone",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2f3f93",
      flipBackgroundPosition: false,
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: "#000000",
      },
      backgroundImagePlacement: {
        x: 600,
        y: 0,
        width: 600,
        height: 630,
        fit: "cover",
        alignX: "center",
        alignY: "center",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 0,
          width: 740,
          height: 78,
          colorRole: "primaryColor",
        },
        {
          type: "rect",
          x: 0,
          y: 552,
          width: 600,
          height: 78,
          colorRole: "primaryColor",
        },
        {
          type: "polygon",
          points: [
            { x: 730, y: 0 },
            { x: 760, y: 0 },
            { x: 615, y: 630 },
            { x: 585, y: 630 },
          ],
          color: "#ffffff",
        },
        {
          type: "polygon",
          points: [
            { x: 0, y: 76 },
            { x: 830, y: 76 },
            { x: 700, y: 554 },
            { x: 0, y: 554 },
          ],
          color: "#d7e8f6",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 1196,
          y2: 28,
          strokeWidth: 5,
          color: "#ffffff",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 28,
          y2: 596,
          strokeWidth: 5,
          color: "#ffffff",
        },
        {
          type: "line",
          x1: 600,
          y1: 596,
          x2: 1196,
          y2: 596,
          strokeWidth: 5,
          color: "#ffffff",
        },
      ],
      icon: {
        x: 554,
        y: 66,
        size: 92,
        iconInset: 22,
        borderColor: "#ffffff",
        borderWidth: 4,
      },
      nameField: {
        font: "700 22px Arial, sans-serif",
        defaultColor: "#2f3f93",
        textTransform: "uppercase",
        letterSpacing: 4,
        x: 88,
        y: 145,
        align: "left",
      },
      mainTextField: {
        font: "700 62px Poppins, Arial, sans-serif",
        defaultColor: "#10233f",
        lineHeight: 72,
        x: 88,
        y: 220,
        align: "left",
        maxWidth: 520,
        maxLines: 4,
        minScale: 0.5,
      },
    },
  }),
  diagonalSplit: makeBlueprintTemplate({
    id: "diagonalSplit",
    name: "Diagonal Split",
    description: "Wide diagonal panel with a strong split-screen reveal",
    defaultName: "GROWTH BLUEPRINT",
    defaultMainText: "Clarify the offer, then let the layout carry the story.",
    iconName: "bolt",
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: blueprintPalette.dark,
      },
      backgroundImagePlacement: {
        x: 780,
        y: 0,
        width: 420,
        height: 630,
        fit: "cover",
        alignX: "center",
        alignY: "center",
      },
      decorations: [
        {
          type: "polygon",
          points: [
            { x: 0, y: 0 },
            { x: 460, y: 0 },
            { x: 736, y: 630 },
            { x: 0, y: 630 },
          ],
          color: blueprintPalette.surface,
        },
        {
          type: "polygon",
          points: [
            { x: 458, y: 0 },
            { x: 490, y: 0 },
            { x: 768, y: 630 },
            { x: 736, y: 630 },
          ],
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 1194,
          y2: 28,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 28,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 596,
          x2: 1194,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 1194,
          y1: 28,
          x2: 1194,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
      ],
      icon: {
        x: 554,
        y: 66,
        size: 92,
        iconInset: 22,
        borderColor: blueprintPalette.frame,
        borderWidth: 4,
      },
      nameField: {
        font: "700 22px Arial, sans-serif",
        defaultColor: blueprintPalette.primary,
        textTransform: "uppercase",
        x: 88,
        y: 150,
        align: "left",
      },
      mainTextField: {
        font: "700 62px Poppins, Arial, sans-serif",
        defaultColor: blueprintPalette.text,
        lineHeight: 72,
        x: 88,
        y: 236,
        align: "left",
        maxWidth: 430,
        maxLines: 4,
        minScale: 0.5,
      },
    },
  }),
  centerDivider: makeBlueprintTemplate({
    id: "centerDivider",
    name: "Center Divider",
    description: "Balanced split layout with a crisp vertical divider",
    defaultName: "CLEAR DIVISION",
    defaultMainText: "Split the message cleanly so the image and copy each get room.",
    iconName: "globe",
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: blueprintPalette.dark,
      },
      backgroundImagePlacement: {
        x: 620,
        y: 0,
        width: 580,
        height: 630,
        fit: "cover",
        alignX: "center",
        alignY: "center",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 0,
          width: 602,
          height: 630,
          color: blueprintPalette.surface,
        },
        {
          type: "rect",
          x: 602,
          y: 0,
          width: 22,
          height: 630,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 1194,
          y2: 28,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 28,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 28,
          y1: 596,
          x2: 1194,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 1194,
          y1: 28,
          x2: 1194,
          y2: 596,
          strokeWidth: 5,
          colorRole: "primaryColor",
        },
      ],
      icon: {
        x: 570,
        y: 40,
        size: 92,
        iconInset: 22,
        borderColor: blueprintPalette.frame,
        borderWidth: 4,
      },
      nameField: {
        font: "700 22px Arial, sans-serif",
        defaultColor: blueprintPalette.primary,
        textTransform: "uppercase",
        x: 88,
        y: 150,
        align: "left",
      },
      mainTextField: {
        font: "700 60px Poppins, Arial, sans-serif",
        defaultColor: blueprintPalette.text,
        lineHeight: 70,
        x: 88,
        y: 234,
        align: "left",
        maxWidth: 430,
        maxLines: 4,
        minScale: 0.5,
      },
    },
  }),
  editorialVeil: makeTemplate({
    id: "editorialVeil",
    name: "Editorial Veil",
    description: "Moody editorial layout with a slanted dusk veil",
    preview: {
      bgGradient: ["#251d31", "#9b8eb8"],
      accentColor: "#6a7d97",
    },
    defaults: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#251d31",
      backgroundGradientCss: gradientCss(135, "#251d31", "#9b8eb8"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#6a7d97",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#6a7d97",
    },
    previewSeed: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#251d31",
      backgroundGradientCss: gradientCss(135, "#251d31", "#9b8eb8"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#6a7d97",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#6a7d97",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 135,
        startColor: "#251d31",
        endColor: "#9b8eb8",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 0,
          width: 1200,
          height: 630,
          color: "rgba(9, 8, 13, 0.18)",
        },
        {
          type: "polygon",
          points: [
            { x: 0, y: 0 },
            { x: 688, y: 0 },
            { x: 820, y: 630 },
            { x: 0, y: 630 },
          ],
          color: "rgba(14, 12, 19, 0.48)",
        },
      ],
      icon: {
        x: 68,
        y: 496,
        size: 92,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 3,
        shadow: {
          color: "rgba(15, 23, 42, 0.24)",
          blur: 22,
          offsetY: 12,
        },
      },
      nameField: {
        font: '700 24px "DM Sans", Arial, sans-serif',
        defaultColor: "#ffffff",
        usePrimaryColor: false,
        x: 178,
        y: 536,
        align: "left",
      },
      mainTextField: {
        font: '400 68px "Playfair Display", Georgia, serif',
        fontWeight: 400,
        defaultColor: "#ffffff",
        lineHeight: 62,
        x: 68,
        y: 182,
        align: "left",
        maxWidth: 520,
        maxLines: 5,
        minScale: 0.48,
      },
    },
  }),
  footerBand: makeTemplate({
    id: "footerBand",
    name: "Footer Band",
    description: "Bold headline layout with a grounded footer strip",
    preview: {
      bgGradient: ["#3a3246", "#a992b8"],
      accentColor: "#c7a07e",
    },
    defaults: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#3a3246",
      backgroundGradientCss: gradientCss(135, "#3a3246", "#a992b8"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#c7a07e",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#4d6d8d",
    },
    previewSeed: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#3a3246",
      backgroundGradientCss: gradientCss(135, "#3a3246", "#a992b8"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#c7a07e",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#4d6d8d",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 135,
        startColor: "#3a3246",
        endColor: "#a992b8",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 0,
          width: 1200,
          height: 508,
          color: "rgba(12, 9, 17, 0.34)",
        },
        {
          type: "rect",
          x: 0,
          y: 508,
          width: 1200,
          height: 122,
          colorRole: "primaryColor",
        },
      ],
      icon: {
        x: 84,
        y: 522,
        size: 92,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 3,
        shadow: {
          color: "rgba(15, 23, 42, 0.18)",
          blur: 18,
          offsetY: 10,
        },
      },
      nameField: {
        font: '700 22px "DM Sans", Arial, sans-serif',
        defaultColor: "#ffffff",
        usePrimaryColor: false,
        x: 198,
        y: 565,
        align: "left",
      },
      mainTextField: {
        font: "700 66px Montserrat, Arial, sans-serif",
        fontWeight: 700,
        defaultColor: "#ffffff",
        lineHeight: 70,
        x: 84,
        y: 182,
        align: "left",
        maxWidth: 850,
        maxLines: 4,
        minScale: 0.48,
      },
    },
  }),
  sunsetArc: makeTemplate({
    id: "sunsetArc",
    name: "Sunset Arc",
    description: "Curved split design with a bright editorial panel",
    preview: {
      bgGradient: ["#7f6fb0", "#f7d7b6"],
      accentColor: "#f57c11",
    },
    defaults: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#7f6fb0",
      backgroundGradientCss: gradientCss(45, "#7f6fb0", "#f7d7b6"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#f57c11",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#f57c11",
      iconBackgroundColor: "#f7f1e7",
    },
    previewSeed: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#7f6fb0",
      backgroundGradientCss: gradientCss(45, "#7f6fb0", "#f7d7b6"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#f57c11",
      mainTextColor: "#ffffff",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#f57c11",
      iconBackgroundColor: "#f7f1e7",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 45,
        startColor: "#7f6fb0",
        endColor: "#f7d7b6",
      },
      decorations: [
        {
          type: "quadratic-panel",
          left: 0,
          top: 0,
          bottom: 630,
          startX: 650,
          controlX: 495,
          controlY: 315,
          endX: 632,
          colorRole: "primaryColor",
        },
        {
          type: "quadratic-curve",
          startX: 650,
          startY: 0,
          controlX: 495,
          controlY: 315,
          endX: 632,
          endY: 630,
          strokeWidth: 12,
          color: "#ffffff",
        },
      ],
      icon: {
        x: 60,
        y: 500,
        size: 92,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 4,
        shadow: {
          color: "rgba(15, 23, 42, 0.2)",
          blur: 18,
          offsetY: 10,
        },
      },
      nameField: {
        font: '700 22px "DM Sans", Arial, sans-serif',
        defaultColor: "#ffffff",
        usePrimaryColor: false,
        x: 174,
        y: 540,
        align: "left",
      },
      mainTextField: {
        font: "700 66px Montserrat, Arial, sans-serif",
        fontWeight: 700,
        textTransform: "uppercase",
        defaultColor: "#ffffff",
        lineHeight: 58,
        x: 60,
        y: 156,
        align: "left",
        maxWidth: 500,
        maxLines: 5,
        minScale: 0.48,
      },
    },
  }),
  softSplit: makeTemplate({
    id: "softSplit",
    name: "Soft Split",
    description: "Soft angled editorial panel with quiet typography",
    preview: {
      bgGradient: ["#efe7d6", "#d2c7eb"],
      accentColor: "#6f655a",
    },
    defaults: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#efe7d6",
      backgroundGradientCss: gradientCss(35, "#efe7d6", "#d2c7eb"),
      surfaceColor: "#efe7d6",
      surfaceOpacity: 1,
      primaryColor: "#6f655a",
      mainTextColor: "#6f655a",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#6f655a",
    },
    previewSeed: {
      name: "Jesse Scott",
      mainText: "The best beaches in St Petersburg and Clearwater, FL - Lonely Planet",
      backgroundType: "gradient",
      backgroundColor: "#efe7d6",
      backgroundGradientCss: gradientCss(35, "#efe7d6", "#d2c7eb"),
      surfaceColor: "#efe7d6",
      surfaceOpacity: 1,
      primaryColor: "#6f655a",
      mainTextColor: "#6f655a",
      iconSource: "lucide",
      iconName: "user",
      iconColor: "#ffffff",
      iconBackgroundColor: "#6f655a",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 35,
        startColor: "#efe7d6",
        endColor: "#d2c7eb",
      },
      decorations: [
        {
          type: "polygon",
          points: [
            { x: 0, y: 0 },
            { x: 822, y: 0 },
            { x: 640, y: 630 },
            { x: 0, y: 630 },
          ],
          colorRole: "surfaceColor",
        },
      ],
      icon: {
        x: 60,
        y: 470,
        size: 92,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 2,
        shadow: {
          color: "rgba(15, 23, 42, 0.1)",
          blur: 14,
          offsetY: 8,
        },
      },
      nameField: {
        font: '700 24px "Open Sans", Arial, sans-serif',
        defaultColor: "#6f655a",
        x: 174,
        y: 510,
        align: "left",
      },
      mainTextField: {
        font: '400 66px "Open Sans", Arial, sans-serif',
        fontWeight: 400,
        defaultColor: "#6f655a",
        lineHeight: 62,
        x: 60,
        y: 170,
        align: "left",
        maxWidth: 500,
        maxLines: 5,
        minScale: 0.48,
      },
    },
  }),
};

export const getTemplate = (templateId) => {
  return templates[templateId] || templates.classic;
};

export const getTemplatePreviewSeed = (templateId) => {
  const template = getTemplate(templateId);
  return template.previewSeed || template.defaults;
};

export const getTemplateList = () => {
  return Object.values(templates).map(
    ({ id, name, description, preview, supportsIcon, defaults }) => ({
      id,
      name,
      description,
      preview,
      supportsIcon,
      defaults,
    })
  );
};
