function gradientCss(angle, startColor, endColor) {
  return `linear-gradient(${angle}deg, ${startColor} 0%, ${endColor} 100%)`;
}

function extractMainTextFontDefaults(fontString) {
  const match = fontString.match(/^(.+?\s)?(\d+)px\s+(.+)$/);
  if (!match) {
    return {
      mainTextFontFamily: "Arial, sans-serif",
      mainTextFontSize: 56,
    };
  }

  return {
    mainTextFontFamily: match[3].trim(),
    mainTextFontSize: parseInt(match[2], 10),
  };
}

function makeTemplate({
  id,
  name,
  description,
  preview,
  defaults,
  config,
  previewSeed,
}) {
  const fontDefaults = extractMainTextFontDefaults(config.mainTextField.font);
  return {
    id,
    name,
    description,
    preview,
    supportsIcon: true,
    defaults: {
      ...defaults,
      mainTextFontFamily:
        defaults.mainTextFontFamily || fontDefaults.mainTextFontFamily,
      mainTextFontSize:
        defaults.mainTextFontSize || fontDefaults.mainTextFontSize,
    },
    config,
    previewSeed: {
      ...previewSeed,
      mainTextFontFamily:
        previewSeed.mainTextFontFamily || fontDefaults.mainTextFontFamily,
      mainTextFontSize:
        previewSeed.mainTextFontSize || fontDefaults.mainTextFontSize,
    },
  };
}

export const templates = {
  classic: makeTemplate({
    id: "classic",
    name: "Classic",
    description: "Clean centered panel with elegant typography",
    preview: {
      bgGradient: ["#e8e4df", "#d4cfc9"],
      accentColor: "#c67c4e",
    },
    defaults: {
      name: "HEALTH AND WELLNESS",
      mainText: "How to Have a Better Work-Life Balance",
      backgroundType: "color",
      backgroundColor: "#e8e4df",
      backgroundGradientCss: gradientCss(45, "#e8e4df", "#d4cfc9"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.85,
      primaryColor: "#c67c4e",
      mainTextColor: "#1a1a1a",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#c67c4e",
    },
    previewSeed: {
      name: "HEALTH AND WELLNESS",
      mainText: "How to Have a Better Work-Life Balance",
      backgroundType: "color",
      backgroundColor: "#e8e4df",
      backgroundGradientCss: gradientCss(45, "#e8e4df", "#d4cfc9"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.85,
      primaryColor: "#c67c4e",
      mainTextColor: "#1a1a1a",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#c67c4e",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 45,
        startColor: "#e8e4df",
        endColor: "#d4cfc9",
      },
      surface: {
        type: "centered",
        height: 340,
        padding: 100,
        defaultColor: "#ffffff",
        defaultOpacity: 0.85,
      },
      icon: {
        x: 554,
        y: 68,
        size: 92,
        iconInset: 22,
        borderColor: "#ffffff",
        borderWidth: 4,
      },
      nameField: {
        font: "500 24px Arial, sans-serif",
        defaultColor: "#c67c4e",
        textTransform: "uppercase",
        letterSpacing: 4,
        offsetY: 70,
      },
      mainTextField: {
        font: '400 64px "Playfair Display", Georgia, serif',
        defaultColor: "#1a1a1a",
        lineHeight: 80,
        offsetY: 80,
        maxWidth: -220,
      },
    },
  }),
  minimal: makeTemplate({
    id: "minimal",
    name: "Minimal",
    description: "Clean editorial layout with subtle accents",
    preview: {
      bgGradient: ["#fafafa", "#f0f0f0"],
      accentColor: "#2563eb",
    },
    defaults: {
      name: "QUIET LUXURY",
      mainText: "Simple design choices that still feel premium",
      backgroundType: "color",
      backgroundColor: "#fafafa",
      backgroundGradientCss: gradientCss(135, "#fafafa", "#f0f0f0"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#2563eb",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "palette",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    previewSeed: {
      name: "QUIET LUXURY",
      mainText: "Simple design choices that still feel premium",
      backgroundType: "color",
      backgroundColor: "#fafafa",
      surfaceColor: "#ffffff",
      surfaceOpacity: 0,
      primaryColor: "#2563eb",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "palette",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: "#fafafa",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 590,
          width: 1200,
          height: 40,
          colorRole: "primaryColor",
        },
        {
          type: "line",
          x1: 100,
          y1: 200,
          x2: 300,
          y2: 200,
          strokeWidth: 3,
          colorRole: "primaryColor",
        },
      ],
      icon: {
        x: 556,
        y: 72,
        size: 88,
        iconInset: 24,
        borderColor: "#ffffff",
        borderWidth: 0,
      },
      nameField: {
        font: "500 16px Arial, sans-serif",
        defaultColor: "#2563eb",
        textTransform: "uppercase",
        letterSpacing: 8,
        x: 100,
        y: 240,
        align: "left",
      },
      mainTextField: {
        font: "400 58px Lora, Georgia, serif",
        defaultColor: "#1f2937",
        lineHeight: 75,
        x: 100,
        y: 320,
        align: "left",
        maxWidth: 860,
      },
    },
  }),
  vibrant: makeTemplate({
    id: "vibrant",
    name: "Vibrant",
    description: "Colorful gradient background with a floating card",
    preview: {
      bgGradient: ["#667eea", "#f093fb"],
      accentColor: "#fbbf24",
    },
    defaults: {
      name: "CREATIVE SYSTEMS",
      mainText: "Build a content engine that feels bright and human",
      backgroundType: "gradient",
      backgroundColor: "#667eea",
      backgroundGradientCss: gradientCss(135, "#667eea", "#f093fb"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.95,
      primaryColor: "#7c3aed",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "star",
      iconColor: "#ffffff",
      iconBackgroundColor: "#f59e0b",
    },
    previewSeed: {
      name: "CREATIVE SYSTEMS",
      mainText: "Build a content engine that feels bright and human",
      backgroundType: "gradient",
      backgroundGradientCss: gradientCss(135, "#667eea", "#f093fb"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.95,
      primaryColor: "#7c3aed",
      mainTextColor: "#1f2937",
      iconSource: "lucide",
      iconName: "star",
      iconColor: "#ffffff",
      iconBackgroundColor: "#f59e0b",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 135,
        startColor: "#667eea",
        endColor: "#f093fb",
      },
      decorations: [
        {
          type: "circle",
          x: 200,
          y: 100,
          radius: 80,
          color: "rgba(255, 255, 255, 0.1)",
        },
        {
          type: "circle",
          x: 1000,
          y: 500,
          radius: 120,
          color: "rgba(255, 255, 255, 0.08)",
        },
        {
          type: "circle",
          x: 900,
          y: 150,
          radius: 40,
          color: "rgba(255, 255, 255, 0.15)",
        },
      ],
      surface: {
        type: "floating",
        x: 100,
        y: 115,
        width: 1000,
        height: 400,
        defaultColor: "#ffffff",
        defaultOpacity: 0.95,
        borderRadius: 24,
        shadow: {
          blur: 60,
          color: "rgba(0, 0, 0, 0.25)",
          offsetY: 20,
        },
      },
      icon: {
        x: 551,
        y: 58,
        size: 98,
        iconInset: 22,
        borderColor: "rgba(255,255,255,0.5)",
        borderWidth: 3,
      },
      nameField: {
        font: "700 16px Arial, sans-serif",
        defaultColor: "#7c3aed",
        textTransform: "uppercase",
        letterSpacing: 6,
        y: 200,
        align: "center",
        badge: {
          enabled: true,
          padding: { x: 20, y: 10 },
          colorRole: "primaryColorSoft",
          borderRadius: 20,
        },
      },
      mainTextField: {
        font: "700 54px Montserrat, Arial, sans-serif",
        defaultColor: "#1f2937",
        lineHeight: 70,
        y: 290,
        align: "center",
        maxWidth: 760,
      },
    },
  }),
  socialMessage: makeTemplate({
    id: "socialMessage",
    name: "Social Message",
    description: "Social media-inspired message card with profile accent",
    preview: {
      bgGradient: ["#0f172a", "#60a5fa"],
      accentColor: "#2563eb",
    },
    defaults: {
      name: "@dailygrace",
      mainText: "Small reminders can reset the whole tone of your day.",
      backgroundType: "gradient",
      backgroundColor: "#0f172a",
      backgroundGradientCss: gradientCss(140, "#0f172a", "#60a5fa"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.97,
      primaryColor: "#2563eb",
      mainTextColor: "#1e293b",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    previewSeed: {
      name: "@dailygrace",
      mainText: "Small reminders can reset the whole tone of your day.",
      backgroundType: "gradient",
      backgroundGradientCss: gradientCss(140, "#0f172a", "#60a5fa"),
      surfaceColor: "#ffffff",
      surfaceOpacity: 0.97,
      primaryColor: "#2563eb",
      mainTextColor: "#1e293b",
      iconSource: "lucide",
      iconName: "sparkles",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2563eb",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "gradient",
        angle: 140,
        startColor: "#0f172a",
        endColor: "#60a5fa",
      },
      decorations: [
        {
          type: "circle",
          x: 1020,
          y: 100,
          radius: 180,
          color: "rgba(255, 255, 255, 0.1)",
        },
        {
          type: "circle",
          x: 140,
          y: 530,
          radius: 150,
          color: "rgba(255, 255, 255, 0.08)",
        },
      ],
      surface: {
        type: "floating",
        x: 90,
        y: 75,
        width: 1020,
        height: 480,
        defaultColor: "#ffffff",
        defaultOpacity: 0.97,
        borderRadius: 36,
        shadow: {
          blur: 60,
          color: "rgba(15, 23, 42, 0.28)",
          offsetY: 24,
        },
      },
      icon: {
        x: 188,
        y: 136,
        size: 112,
        iconInset: 28,
        borderColor: "#ffffff",
        borderWidth: 8,
        shadow: {
          color: "rgba(15, 23, 42, 0.18)",
          blur: 24,
          offsetY: 12,
        },
      },
      nameField: {
        font: "700 30px Arial, sans-serif",
        defaultColor: "#2563eb",
        x: 314,
        y: 190,
        align: "left",
      },
      mainTextField: {
        font: '400 56px "DM Sans", Arial, sans-serif',
        defaultColor: "#1e293b",
        lineHeight: 66,
        x: 150,
        y: 320,
        align: "left",
        maxWidth: 860,
        maxLines: 4,
        minScale: 0.42,
      },
      subtitle: {
        enabled: true,
        font: "500 20px Arial, sans-serif",
        color: "#64748b",
        x: 150,
        y: 485,
        align: "left",
        text: "Reply  •  Share  •  Save",
      },
    },
  }),
  angledFrame: makeTemplate({
    id: "angledFrame",
    name: "Angled Frame",
    description: "Sharp geometric banner with a slanted content panel",
    preview: {
      bgGradient: ["#2f3f93", "#000000"],
      accentColor: "#2f3f93",
    },
    defaults: {
      name: "MARKETING INSIGHT",
      mainText: "Turn one strong message into a design system that scales.",
      backgroundType: "color",
      backgroundColor: "#000000",
      backgroundGradientCss: gradientCss(120, "#2f3f93", "#000000"),
      surfaceColor: "#d7e8f6",
      surfaceOpacity: 1,
      primaryColor: "#2f3f93",
      mainTextColor: "#10233f",
      iconSource: "lucide",
      iconName: "megaphone",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2f3f93",
    },
    previewSeed: {
      name: "MARKETING INSIGHT",
      mainText: "Turn one strong message into a design system that scales.",
      backgroundType: "color",
      backgroundColor: "#000000",
      surfaceColor: "#d7e8f6",
      surfaceOpacity: 1,
      primaryColor: "#2f3f93",
      mainTextColor: "#10233f",
      iconSource: "lucide",
      iconName: "megaphone",
      iconColor: "#ffffff",
      iconBackgroundColor: "#2f3f93",
    },
    config: {
      canvas: { width: 1200, height: 630 },
      backgroundFallback: {
        type: "color",
        color: "#000000",
      },
      backgroundImagePlacement: {
        x: 600,
        y: 0,
        width: 600,
        height: 630,
        fit: "cover",
        alignX: "center",
        alignY: "center",
      },
      decorations: [
        {
          type: "rect",
          x: 0,
          y: 0,
          width: 740,
          height: 78,
          colorRole: "primaryColor",
        },
        {
          type: "rect",
          x: 0,
          y: 552,
          width: 600,
          height: 78,
          colorRole: "primaryColor",
        },
        {
          type: "polygon",
          points: [
            { x: 730, y: 0 },
            { x: 760, y: 0 },
            { x: 615, y: 630 },
            { x: 585, y: 630 },
          ],
          color: "#ffffff",
        },
        {
          type: "polygon",
          points: [
            { x: 0, y: 76 },
            { x: 830, y: 76 },
            { x: 700, y: 554 },
            { x: 0, y: 554 },
          ],
          color: "#d7e8f6",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 1196,
          y2: 28,
          strokeWidth: 5,
          color: "#ffffff",
        },
        {
          type: "line",
          x1: 28,
          y1: 28,
          x2: 28,
          y2: 596,
          strokeWidth: 5,
          color: "#ffffff",
        },
        {
          type: "line",
          x1: 600,
          y1: 596,
          x2: 1196,
          y2: 596,
          strokeWidth: 5,
          color: "#ffffff",
        },
      ],
      icon: {
        x: 554,
        y: 66,
        size: 92,
        iconInset: 22,
        borderColor: "#ffffff",
        borderWidth: 4,
      },
      nameField: {
        font: "700 22px Arial, sans-serif",
        defaultColor: "#2f3f93",
        textTransform: "uppercase",
        letterSpacing: 4,
        x: 88,
        y: 145,
        align: "left",
      },
      mainTextField: {
        font: "700 62px Poppins, Arial, sans-serif",
        defaultColor: "#10233f",
        lineHeight: 72,
        x: 88,
        y: 220,
        align: "left",
        maxWidth: 455,
        maxLines: 4,
        minScale: 0.5,
      },
    },
  }),
};

export const getTemplate = (templateId) => {
  return templates[templateId] || templates.classic;
};

export const getTemplatePreviewSeed = (templateId) => {
  const template = getTemplate(templateId);
  return template.previewSeed || template.defaults;
};

export const getTemplateList = () => {
  return Object.values(templates).map(
    ({ id, name, description, preview, supportsIcon, defaults }) => ({
      id,
      name,
      description,
      preview,
      supportsIcon,
      defaults,
    })
  );
};
